<a href="https://colab.research.google.com/github/Ashwitharavula/aiml/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
a=['ashu','deepa','palomi','anjali']
print(a)
print(a[2])
a.append('shushu')
print(a)
a[2] = 'chinnu'
print(a)
print(type(a))
print(len(a))

['ashu', 'deepa', 'palomi', 'anjali']
palomi
['ashu', 'deepa', 'palomi', 'anjali', 'shushu']
['ashu', 'deepa', 'chinnu', 'anjali', 'shushu']
<class 'list'>
5


In [35]:
import numpy as np
num_array=np.array([1,2,3,4,5])
print(num_array)
print(type(num_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [38]:

import numpy as np
num=np.array([1,2,3,4])
print(num)
print(type(num))

[1 2 3 4]
<class 'numpy.ndarray'>


In [50]:
import numpy as np
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
print(array1*array2)
print(array1/array2)
print(np.power(array1,2))

[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [47]:
import numpy as np
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
print("addition of two numbers:",array1+array2)

addition of two numbers: [ 6  8 10 12]


In [48]:
import numpy as np
my_array=([1,2,3,4])
sin=np.sin(my_array)
print(sin)
log=np.log(my_array)
print(log)
log2=np.log2(my_array)
print(log2)
exp=np.exp(my_array)
print(exp)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]
